//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoCleziel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public int IdProduto { get; set; }
        public string NomeProduto { get; set; }
        public string Descricao { get; set; }
        public string ImagemUrl { get; set; }
        public Nullable<decimal> Preco { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public Nullable<int> Estoque { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public Nullable<bool> Disponibilidade { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
