//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoCleziel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int IdUsuario { get; set; }
        public string PrimeiroNome { get; set; }
        public string UltimoNome { get; set; }
        public Nullable<System.DateTime> DataNasc { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }
        public Nullable<System.DateTime> UltimoAcesso { get; set; }
        public int PerfilUsuarioID { get; set; }
        public string Rua { get; set; }
    
        public virtual PerfilUsuario PerfilUsuario { get; set; }
    }
}
